kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Release.Name }}-osbuild-worker-ansible
spec:
  runPolicy: Serial
  source:
    type: Dockerfile
    dockerfile: |
      FROM registry.access.redhat.com/ubi8/python-38
      USER 0
      RUN dnf install skopeo -y && \
          pip install --upgrade pip && \
          pip install openshift && \
          pip install jmespath && \
          pip install netaddr && \
          pip install ansible==2.9.* && \
          curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | \
            tar -xvzf - -C /usr/local/bin/ oc && chmod 755 /usr/local/bin/oc && ln -s /usr/local/bin/oc /usr/local/bin/kubectl
      USER 1001
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/python-38:latest
  triggers:
    - type: ConfigChange
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Release.Name }}-osbuild-worker-ansible:latest
