apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redhat-portal-credentials
type: Opaque
data:
  username: {{ required "RedHat Username is required" .Values.redhat.username | b64enc | quote }}
  password: {{ required "RedHat Password is required" .Values.redhat.password | b64enc | quote }}
  pool_id: {{ required "RedHat Pool ID is required" .Values.redhat.pool_id | b64enc | quote }}
  offline_token: {{ required "RedHat Offline Token is required" .Values.redhat.offline_token | b64enc | quote }}

