apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-osbuild-worker-setup-ansible
data:
{{ (tpl (.Files.Glob "config/playbook.yml").AsConfig .) | indent 2 }}
{{ (tpl (.Files.Glob "config/requirements.yml").AsConfig .) | indent 2 }}
{{ (tpl (.Files.Glob "config/ansible.cfg").AsConfig .) | indent 2 }}
