{{- $publicKey := .Files.Glob (printf "files/ssh/%s" .Values.ssh.publickey_filename) }}
{{- $privateKey := .Files.Glob (printf "files/ssh/%s" .Values.ssh.privatekey_filename) }}
{{- if and ($publicKey) ($privateKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-osbuild-worker-ssh-key
type: Opaque
data:
  ssh-publickey: {{ .Files.Get (printf "files/ssh/%s" .Values.ssh.publickey_filename) | b64enc | quote }}
  ssh-privatekey: {{ .Files.Get (printf "files/ssh/%s" .Values.ssh.privatekey_filename) | b64enc | quote }}
{{- else }}
{{ fail "Composer Certificates were not provided" }}
{{- end }}
