apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  annotations:
    description: OSBuild Worker
    name.os.template.kubevirt.io/rhel8.5: "Red Hat Enterprise Linux 8.0 or higher"
  name: {{ .Release.Name }}-osbuild-worker
  labels:
    app: osbuild-worker
    workload.template.kubevirt.io/server: "true"
    os.template.kubevirt.io/rhel8.5: "true"
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1alpha1
    kind: DataVolume
    metadata:
      creationTimestamp: null
      name: {{ .Release.Name }}-image-builder-rootdisk
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
          volumeMode: Filesystem
      source:
        http:
          url: {{ .Values.vm.image_url }}
  runStrategy: Always
  template:
    metadata:
      labels:
        app: osbuild-worker
        kubevirt.io/domain: osbuild-worker
        vm.kubevirt.io/name: osbuild-worker
        workload.template.kubevirt.io/server: "true"
        os.template.kubevirt.io/rhel8.5: 'true'
    spec:
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          - disk:
              bus: virtio
            name: redhat-portal-credentials
            serial: rhpc
          - disk:
              bus: virtio
            name: image-builder-ssh-key
            serial: ibsk
          - disk:
              bus: virtio
            name: serviceaccount
            serial: seac
          - disk:
              bus: virtio
            name: osbuild-worker-certs
            serial: obwc
          - disk:
              bus: virtio
            name: osbuild-worker-config
            serial: obwt
          interfaces:
          - masquerade: {}
            model: virtio
            name: nic-0
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel8.4.0
        resources:
          requests:
            memory: 8Gi
      hostname: osbuild-worker
      networks:
      - name: nic-0
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: {{ .Release.Name }}-image-builder-rootdisk
        name: rootdisk
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            name: default
            hostname: {{ .Release.Name }}-image-builder
            user: cloud-user
            bootcmd:
            - "mkdir -p /home/cloud-user/.ssh && chown -R 1000:1000 /home/cloud-user"
            - "mkdir -p /var/secrets/{redhat-portal-credentials,image-builder-ssh-key,serviceaccount,osbuild-worker-certs}"
            - "mount -o overriderockperm,mode=0400,uid=0,gid=0 /dev/disk/by-id/virtio-rhpc /var/secrets/redhat-portal-credentials"
            - "mount -o overriderockperm,mode=0400,uid=0,gid=0 /dev/disk/by-id/virtio-ibsk /var/secrets/image-builder-ssh-key"
            - "mount -o overriderockperm,mode=0400,uid=0,gid=0 /dev/disk/by-id/virtio-seac /var/secrets/serviceaccount"
            - "mount -o overriderockperm,mode=0400,uid=0,gid=0 /dev/disk/by-id/virtio-obwc /var/secrets/osbuild-worker-certs"
            - "cp /var/secrets/image-builder-ssh-key/ssh-publickey /home/cloud-user/.ssh/authorized_keys"
            - "chmod 644 /home/cloud-user/.ssh/authorized_keys"
            - "mkdir -p /etc/osbuild-composer/"
            - "cp /var/secrets/osbuild-worker-certs/* /etc/osbuild-composer/"
            - "mkdir -p /etc/osbuild-worker"
            - "mount -o overriderockperm,mode=0644,uid=0,gid=0 /dev/disk/by-id/virtio-obwt /etc/osbuild-worker"
        name: cloudinitdisk
      - name: redhat-portal-credentials
        secret:
          secretName: {{ .Release.Name }}-redhat-portal-credentials
      - name: image-builder-ssh-key
        secret:
          secretName: {{ .Release.Name }}-osbuild-worker-ssh-key
      - name: serviceaccount
        serviceAccount:
          serviceAccountName: {{ .Release.Name }}-osbuild-worker
      - name: osbuild-worker-certs
        secret:
          secretName: {{ .Release.Name }}-osbuild-worker-certs
      - name: osbuild-worker-config
        configMap:
          name: {{ .Release.Name }}-osbuild-worker-config
