apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-composer-db
type: Opaque
data:
  db.host: {{ required "DB Host is required" .Values.db.host | b64enc | quote }}
  db.port: {{ required "DB Port is required" .Values.db.port | b64enc | quote }}
  db.name: {{ required "DB Name is required" .Values.db.name | b64enc | quote}}
  db.user: {{ required "DB Username is required" .Values.db.user | b64enc | quote}}
  db.password: {{ required "DB Password is required" .Values.db.password | b64enc | quote}}
