{{- $caCert := .Files.Glob (printf "files/certs/%s" .Values.certs.ca_certificate_filename) }}
{{- $composerCert := .Files.Glob (printf "files/certs/%s" .Values.certs.composer_certificate_filename) }}
{{- $composerKey := .Files.Glob (printf "files/certs/%s" .Values.certs.composer_key_filename) }}
{{- if and ($caCert) ($composerCert) ($composerKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-osbuild-composer-secrets
type: Opaque
data:
  ca-crt.pem: {{ .Files.Get (printf "files/certs/%s" .Values.certs.ca_certificate_filename) | b64enc | quote }}
  composer-crt.pem: {{ .Files.Get (printf "files/certs/%s" .Values.certs.composer_certificate_filename) | b64enc | quote }}
  composer-key.pem: {{ .Files.Get (printf "files/certs/%s" .Values.certs.composer_key_filename) | b64enc | quote }}
{{- else }}
{{ fail "Composer Certificates were not provided" }}
{{- end }}