apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: osbuild-composer
  name: {{ .Release.Name }}-composer
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: osbuild-composer
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: osbuild-composer
    spec:
      containers:
      - env:
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              key: db.host
              name: {{ .Release.Name }}-composer-db
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              key: db.port
              name: {{ .Release.Name }}-composer-db
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              key: db.name
              name: {{ .Release.Name }}-composer-db
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              key: db.user
              name: {{ .Release.Name }}-composer-db
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: db.password
              name: {{ .Release.Name }}-composer-db
        - name: PGSSLMODE
          value: {{ .Values.deployment.composer.pgsslmode }}
        - name: PGMAXCONNS
          value: {{ .Values.deployment.composer.pgmaxconns | quote }}
        image: {{ .Values.deployment.composer.image_name }}:{{ .Values.deployment.composer.image_tag }}
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/osbuild-composer-live
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: composer
        ports:
        - containerPort: {{ .Values.ports.composer_api_internal }}
          name: composer-api
          protocol: TCP
        - containerPort: {{ .Values.ports.worker_api_internal }}
          name: worker-api
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          tcpSocket:
            port: composer-api
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: {{ .Values.deployment.composer.cpu_limit }}
            memory: {{ .Values.deployment.composer.memory_limit }}
          requests:
            cpu: {{ .Values.deployment.composer.cpu_request }}
            memory: {{ .Values.deployment.composer.memory_request }}
        volumeMounts:
        - mountPath: /var/lib/osbuild-composer
          name: state-directory
        - mountPath: /var/cache/osbuild-composer
          name: cache-directory
        - mountPath: /etc/osbuild-composer
          name: composer-config
      - image: {{ .Values.deployment.proxy.image_name }}:{{ .Values.deployment.proxy.image_tag }}
        name: proxy
        ports:
        - containerPort: {{ .Values.ports.composer_api_external }}
          name: composer-api
          protocol: TCP
        - containerPort: {{ .Values.ports.worker_api_external }}
          name: worker-api
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          tcpSocket:
            port: composer-api
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: {{ .Values.deployment.proxy.certs_dir }}
          name: composer-secrets
        - mountPath: /etc/envoy
          name: proxy-config
      initContainers:
      - command:
        - /opt/migrate/tern
        - migrate
        - -m
        - /opt/migrate/schemas
        env:
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              key: db.host
              name: {{ .Release.Name }}-composer-db
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              key: db.port
              name: {{ .Release.Name }}-composer-db
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              key: db.name
              name: {{ .Release.Name }}-composer-db
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              key: db.user
              name: {{ .Release.Name }}-composer-db
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: db.password
              name: {{ .Release.Name }}-composer-db
        - name: PGSSLMODE
          value: {{ .Values.pgsslmode }}
        image: {{ .Values.deployment.composer.image_name }}:{{ .Values.deployment.composer.image_tag }}
        name: composer-migrate
      serviceAccountName: {{ .Release.Name }}-image-builder
      volumes:
      - name: composer-config
        configMap:
          name: {{ .Release.Name }}-osbuild-composer-config
      - name: composer-secrets
        secret:
          secretName: {{ .Release.Name }}-osbuild-composer-secrets
      - configMap:
          name: {{ .Release.Name }}-osbuild-composer-proxy-config
        name: proxy-config
      - emptyDir: {}
        name: state-directory
      - emptyDir: {}
        name: cache-directory
