apiVersion: v1
kind: Service
metadata:
  labels:
    app: composer
    composerInstance: {{ .Values.composer_instance_label }}
    port: composer-api
    template: composer
  name: image-builder-composer
spec:
  ports:
  - name: composer-api
    port: 80
    protocol: TCP
    targetPort: {{ .Values.composer_api_port }}
  selector:
    app: composer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: composer
    composerInstance: {{ .Values.composer_instance_label }}
    port: worker-api
    template: composer
  name: image-builder-worker
spec:
  ports:
  - name: worker-api
    port: 80
    protocol: TCP
    targetPort: {{ .Values.worker_api_port }}
  selector:
    app: composer
