apiVersion: v1
imagePullSecrets:
- name: quay-cloudservices-pull
kind: ServiceAccount
metadata:
  labels:
    composerInstance: {{ .Values.composer_instance_label }}
    template: composer
  name: {{ .Release.Name }}-image-builder
