apiVersion: v1
kind: Service
metadata:
  labels:
    app: composer
    port: composer-api
  name: image-builder-composer
spec:
  ports:
  - name: composer-api
    port: 443
    protocol: TCP
    targetPort: {{ .Values.ports.composer_api_external }}
  selector:
    app: osbuild-composer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: composer
    port: worker-api
  name: image-builder-worker
spec:
  ports:
  - name: worker-api
    port: 443
    protocol: TCP
    targetPort: {{ .Values.ports.worker_api_external }}
  selector:
    app: osbuild-composer
