deployment:
  replicas: 3
  composer:
    image_name: quay.io/app-sre/composer
    image_tag: '# TODO: must define a default value for .image_tag'
    cpu_limit: "1"
    cpu_request: 200m
    memory_limit: 512Mi
    memory_request: 256Mi
    pgmaxconns: "20"
    pgsslmode: require
  proxy:
    image_name: envoyproxy/envoy
    image_tag: v1.21-latest
    certs_dir: /etc/certs
ports:
  composer_api_external: "8080"
  composer_api_internal: "18080"
  worker_api_external: "8700"
  worker_api_internal: "18700"
composer_config:
  koji:
    log_level: "info"
  worker:
    log_level: "info"
    request_job_timeout: "30s"
    base_path: "/api/worker/v1"
certs:
  composer_certificate_filename: composer-crt.pem
  composer_key_filename: composer-key.pem
  ca_certificate_filename: ca-crt.pem
composer_config_bucket_name: imagebuilder.service.staging
composer_config_dir: /etc/osbuild-composer
db:
  host: postgresql
  port: "5432"

koji_enable_jwt: "false"
# liveness_uri: /api/image-builder-composer/v2/openapi




rh_sso_base_url: https://sso.redhat.com/auth/realms/redhat-external
worker_api_enable_jwt: "false"
